image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.3"

stages:
  - uatBuild
  - releaseBuild
  
cache:
  paths:
    - .gradle/
    - .m2/
    - android-sdk-linux/
    - android-sdk.zip


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - if [ ! -e android-sdk.zip ]; then wget --quiet -nc --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip ; fi
  - unzip -q -n android-sdk.zip -d android-sdk-linux
  - mkdir -p android-sdk-linux/licenses
  - printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > android-sdk-linux/licenses/android-sdk-license
  - printf "84831b9409646a918e30573bab4c9c91346d8abd" > android-sdk-linux/licenses/android-sdk-preview-license
  - android-sdk-linux/tools/bin/sdkmanager --update > update.log
  - android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew

uatBuild:
  stage: uatBuild
  script:
    - ./gradlew assembleUat
  tags:
    - build

  artifacts:
    name: "${CI_BUILD_NAME}"
    paths:
    - app/build/outputs/apk/uat/
    - app/build/outputs/mapping/uat/

releaseBuild:
  stage: releaseBuild
  script:
    - ./gradlew assembleRelease
  tags:
    - build

  artifacts:
    name: "${CI_BUILD_NAME}"
    paths:
    - app/build/outputs/apk/release/
    - app/build/outputs/mapping/release/